In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets

In [3]:
digits = datasets.load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

In [4]:
n_samples = len(digits.images)
features = digits.images.reshape((n_samples, -1))

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split( features, digits.target, test_size = 0.3,stratify = digits.target, random_state = 123 )

In [7]:
from sklearn.naive_bayes import GaussianNB

In [8]:
gnb = GaussianNB()

In [9]:
model = gnb.fit(X_train, y_train)

In [10]:
y_pred = gnb.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [12]:
print(accuracy_score(y_test, y_pred))

0.8351851851851851


In [13]:
print(confusion_matrix(y_test,y_pred))

[[53  0  0  0  0  0  0  1  0  0]
 [ 0 47  0  0  0  0  2  1  2  3]
 [ 0  7 25  0  0  0  1  0 20  0]
 [ 0  0  0 49  0  0  0  3  3  0]
 [ 0  0  0  0 44  0  4  5  1  0]
 [ 0  1  0  1  0 46  2  3  2  0]
 [ 0  1  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  1  0  0 52  0  1]
 [ 0  4  0  1  0  0  0  4 43  0]
 [ 0  1  1  2  1  0  0  4  6 39]]


In [14]:
print(classification_report(y_test, y_pred ))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        54
           1       0.77      0.85      0.81        55
           2       0.96      0.47      0.63        53
           3       0.92      0.89      0.91        55
           4       0.96      0.81      0.88        54
           5       1.00      0.84      0.91        55
           6       0.85      0.98      0.91        54
           7       0.71      0.96      0.82        54
           8       0.56      0.83      0.67        52
           9       0.91      0.72      0.80        54

    accuracy                           0.84       540
   macro avg       0.86      0.83      0.83       540
weighted avg       0.87      0.84      0.83       540

